platform: linux
      
image_resource:
  type: registry-image
  source:
      repository: alpine/git
inputs:
- name: repo
outputs:
- name: repo
params:
  EMAIL: bappy776@gmail.com
  GIT_AUTHOR_NAME: bappy776
run:
  path: repo/tasks/concourse-sh.sh
