resources:
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: git@github.com:bappy776/examples.git

jobs:
- name: configure-pipelines
  public: true
  plan:
    - get: concourse-examples
      trigger: true
    - set_pipeline: hello-world
      file: pipelines/hello-world.yml